Added all API Kodi commands
MarvinSchenkel/HomeyKodi pull request #8
Opened 2017-05-11 15:36 UTC by DarkCinema

With this code I added the ability to send all available input commands.

2017-06-03 02:44 UTC, MarvinSchenkel requested changes
Hey mate, thanks for your PR. Could you make the following changes before I merge it:
- put the list KODIcommands / GUIwinarray in a separate json file 
- make use of the kodi library for GUI actions rather than the http. This would mean we'd be interacting with Kodi in two different ways

2017-06-03 02:49 UTC, MarvinSchenkel requested changes
Also, please use the standardjs coding guidelines like in the rest of the app. There are two coding styles throughout the whole app at the moment

2017-06-03 02:49 UTC, MarvinSchenkel commented on app.js
> -var Utils = require('../../libs/utils')
Please remove this empty line

2017-06-03 02:49 UTC, MarvinSchenkel commented on app.js
> +var guiid = 10000
Scope to the function and use const instead of a global var

2017-06-03 02:49 UTC, MarvinSchenkel commented on app.js
> +var KODIcommands = [
Move to a separate json file

2017-06-03 02:49 UTC, MarvinSchenkel commented on app.js
> +var GUIWinarray = [
Move to a separate json file

2017-06-03 02:49 UTC, MarvinSchenkel commented on app.json
> -  "id": "nl.marvinschenkel.kodi",
Undo this extra space

2017-06-03 02:49 UTC, MarvinSchenkel commented on drivers/kodi/driver.js
> +const http = require('http');
Try to use the KodiWs instead of http lib to have 1 way of communicating with Kodi

2017-06-03 02:49 UTC, MarvinSchenkel commented on drivers/kodi/driver.js
> +var guiid = 10000
Scope to the function and use cons

2017-06-06 19:22 UTC, DarkCinema commented on drivers/kodi/driver.js
> +const http = require('http');
I need to use http since the most "GUI.ActivateWindow" json commands lock up the TCP stack.
I can't find any solution to solve this with RPC.

2018-05-20 16:59 UTC, MarvinSchenkel commented
Closing this PR because it's deprecated with the new app version. Thanks for the support!

2018-05-20 16:59 UTC, closed without merging